### ISSUE TITLE
`asdict` fails for attributes of type Mapping with keys of type `Tuple`

### ISSUE THREAD

**Issue by radugrosu** [python-attrs/attrs#646]
```
@attr.s
class A:
    a = attr.ib()
        
instance = A({(1, ): 1})
attr.asdict(instance)
```
produces: 
`TypeError: unhashable type: 'list'` 

when the `retain_collection_types` flag is set to false (the default).  This can take a while to figure out, since the error is not the most descriptive (and the classes are not toy examples like this one).
I just thought it would be worth mentioning. In any case, thanks for this awesome library.

**Comment by tovrstra** [comment]
I stumbled upon the same issue and it is indeed not easy to figure out what is going wrong. I'm trying to think how this could be fixed. @hynek Could you comment on the following? Thanks!

- Would it be acceptable to change the default value for `retain_collection_types` to `True`? This would reduce the likelihood of this issue to appear unexpectedly. It is not a full fix though.

- Would it be ok to use `tuple` as default collection type, when `retain_collection_types=False`? I would expect this to completely resolve the issue.

**Comment by hynek** [comment]
We cannot change the defaults for attr.asdict due to backward compatibility but we can do that for the upcoming attrs.asdict.

**Comment by tovrstra** [comment]
@hynek I understand. I've been thinking about related corner cases for `asdict`, which may also be addressed when making a newer version.

Frozen sets are not changed into a default collection type, while sets are:

```python
>>> import attr
>>> @attr.s
... class A:
...     a = attr.ib()
... 
>>> instance = A(frozenset([1, 2]))
>>> attr.asdict(instance)
{'a': frozenset({1, 2})}
>>>
>>> instance = A(set([1, 2]))
>>> attr.asdict(instance)
{'a': [1, 2]}
>>>
```

This type of behavior can be made consistent in general by checking whether objects are instances of the classes defined in [collections.abc](https://docs.python.org/3/library/collections.html#collections.Counter).

(Before making a new version, it would also be useful to understand the motivation for the current behavior.)

**Comment by hynek** [comment]
I have just merged #704 that fixes the frozenset issue – sorry for the late reply!

**Comment by hynek** [comment]
I have created a new issue for the new defaults, so closing this one.

**Comment by tovrstra** [comment]
No problem. Thank you for fixing!

**Comment by ikalnytskyi** [comment]
I think I still experience this issue on latest stable `attrs == 21.2.0`. Is this expected?


```python
import attr

@attr.s
class Test:
    x = attr.ib()

t = Test(x={(1, 2): 3})
attr.asdict(t)
```

```
Traceback (most recent call last):
  File "/tmp/t.py", line 11, in <module>
    attr.asdict(t)
  File "/tmp/.venv/lib/python3.9/site-packages/attr/_funcs.py", line 86, in asdict
    rv[a.name] = df(
TypeError: unhashable type: 'list'
```

**Comment by hynek** [comment]
You have to pass `retain_collection_types=True` because we can't change the default value – that would be a very breaking change.

We intend to change it when you can import it from [`attrs`](https://www.attrs.org/en/stable/changelog.html#deprecations). I hope I'll get to it later this year.
